image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - make build-prod
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master