image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - mv out/* public/.
  artifacts:
    paths:
      - public
  only:
    - master